export const occasions = [
  {
    title: "Happy Birthdays",
    description: "Celebrate special birthdays with heartfelt video messages from friends and family.",
    icon: "🎂",
    image: "/images/landing/occasions/birthday.png",
    bgColor: "bg-[#FFF9F2]",
    id: "birthday",
  },
  {
    title: "Weddings",
    description: "Create unforgettable wedding Tributes with messages from loved ones near and far.",
    icon: "👰",
    image: "/images/landing/occasions/wedding.png",
    bgColor: "bg-[#FFF5F8]",
    id: "wedding",
  },
  {
    title: "Anniversaries",
    description: "Honor milestone anniversaries with personalized video collections from colleagues and friends.",
    icon: "🍾",
    image: "/images/landing/occasions/anniversary.png",
    bgColor: "bg-[#F0FFF4]",
    id: "anniversary",
  },
  {
    title: "Retirements",
    description: "Send off retiring colleagues with meaningful video Tributes celebrating their career.",
    icon: "🎉",
    image: "/images/landing/occasions/retirement.png",
    bgColor: "bg-[#F0F7FF]",
    id: "retirement",
  },
  {
    title: "In Memory",
    description: "Create touching memorial Tributes to honor and remember loved ones who have passed.",
    icon: "🕯️",
    image: "/images/landing/occasions/memorial.png",
    bgColor: "bg-[#F7F2FF]",
    id: "memorial",
  },
  {
    title: "Graduations",
    description: "Congratulate graduates with inspiring video messages from family and friends.",
    icon: "🎓",
    image: "/images/landing/occasions/graduation.png",
    bgColor: "bg-[#F5F2FF]",
    id: "graduation",
  },
  {
    title: "Teacher Appreciation",
    description: "Show gratitude to educators with heartfelt video Tributes from students and parents.",
    icon: "🫶",
    image: "/images/landing/occasions/retirement.png",
    bgColor: "bg-[#FFF9F0]",
    id: "teacher_appreciation",
  },
  {
    title: "Promotions",
    description: "Celebrate career advancements with congratulatory video messages from teammates.",
    icon: "⭐",
    image: "/images/landing/occasions/graduation.png",
    bgColor: "bg-[#FFFFF0]",
    id: "promotion",
  },
  {
    title: "Get Well Soon",
    description: "Send healing wishes and support through uplifting video messages during recovery.",
    icon: "❤️",
    image: "/images/landing/occasions/memorial.png",
    bgColor: "bg-[#FFF0F0]",
    id: "get_well_soon",
  },
  {
    title: "New Baby",
    description: "Welcome new arrivals with warm video congratulations from family and friends.",
    icon: "🧸",
    image: "/images/landing/occasions/baby.png",
    bgColor: "bg-[#F0FBFF]",
    id: "new_baby",
  },
];
